
package usingteste;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Testando", targetNamespace = "http://teste/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Testando {


    /**
     * 
     * @param param1
     * @return
     *     returns int
     */
    @WebMethod(operationName = "TestandoOp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TestandoOp", targetNamespace = "http://teste/", className = "usingteste.TestandoOp")
    @ResponseWrapper(localName = "TestandoOpResponse", targetNamespace = "http://teste/", className = "usingteste.TestandoOpResponse")
    public int testandoOp(
        @WebParam(name = "param1", targetNamespace = "")
        String param1);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "TestandoOp1")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TestandoOp1", targetNamespace = "http://teste/", className = "usingteste.TestandoOp1")
    @ResponseWrapper(localName = "TestandoOp1Response", targetNamespace = "http://teste/", className = "usingteste.TestandoOp1Response")
    public int testandoOp1();

}
